trigger:
- develop
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.15.0'
  displayName: 'Install Node.js'

- script: |
    npm config set user root && sudo npm cache clean -f && npm install -g --unsafe-perm node-sass && sudo npm install
  displayName: 'npm install'

#- script: |
#    npm run security:audit
#  displayName: 'Run npm dependancy security audit'

- script: |
    npm run test:unit
  displayName: 'Run unit test'